<a href="https://colab.research.google.com/github/ayushipradhan30/Python/blob/main/Python_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [ ]:
#Create a 1D NumPy array of numbers from 0 to 9
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Convert 1D array to 2D
arr = np.arange(6)
print(arr)
print(arr.reshape(2,3))

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [ ]:
#Print Array Attributes
'''
The shape of the array.
The number of array dimensions.
The size of each element in bytes.
'''
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)

print("Shape: ", arr.shape)
print("array dimensions: ", arr.ndim)
print("Item size: ", arr.itemsize)

Shape:  (4, 2)
array dimensions:  2
Item size:  2


In [ ]:
#Create a 3×3 NumPy array of all True
print(np.ones((3,3), dtype = bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#Extract the documentation of NumPy’s arange() function
np.info(np.arange(0))

class:  ndarray
shape:  (0,)
strides:  (0,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0xac89aa0
byteorder:  little
byteswap:  False
type: int64


In [ ]:
#Create a 1D array filled with zeros and another filled with ones
print(np.zeros(5))
print(np.ones(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [ ]:
#Create a 1D array of 10 evenly spaced values between 5 and 50
print(np.linspace(5,50,10))

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [ ]:
#Convert a Python list into a NumPy array
l = [1, 2, 3, 4, 5]
print(np.array(l))

[1 2 3 4 5]


In [ ]:
#Find the memory size of a NumPy array of numbers from 0 to 9
arr = np.arange(10)
print(arr)
print(arr.nbytes)

[0 1 2 3 4 5 6 7 8 9]
80


In [ ]:
#Reverse a 1D NumPy array
arr = np.arange(10)
print(arr)
print(arr[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [ ]:
#Create a 3×3 identity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Create a 4×4 array and extract its first row and last column
arr = np.array([
    [3, 6, 9, 12],
    [15, 18, 21, 24],
    [27, 30, 33, 36],
    [39, 42, 45, 48],
    [51, 54, 57, 60]
])
new_arr = arr[1::2, ::2]
print(new_arr)

[[15 21]
 [39 45]]


In [3]:
#Replace all odd numbers in a NumPy array with -1
arr = np.arange(1,11)
print(arr)

arr[arr % 2 == 1] = -1
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [4]:
#Get the indices of non-zero elements in an array
arr = np.array([1, 0, 2, 0, 3, 0, 4])
print(arr)
print(np.nonzero(arr))

[1 0 2 0 3 0 4]
(array([0, 2, 4, 6]),)


In [2]:
#Find the common items between two arrays
a = np.array([1, 2, 3, 2, 8, 4, 2, 4])
b = np.array([2, 4, 5, 6, 8])
print(np.intersect1d(a,b))

[2 4 8]


In [3]:
#Perform arithmetic operations on two NumPy arrays element-wise
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sum = np.add(a,b)
mul = np.multiply(a,b)

print("Sum: ",sum)
print("Mul: ",mul)

Sum:  [5 7 9]
Mul:  [ 4 10 18]


In [4]:
#Matrix multiplication
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a,b))

32


In [7]:
#Compute the mean, median, and standard deviation of a NumPy array
arr = np.array([10, 20, 30, 100, 200, 300])
print("Mean: ",np.mean(arr))
print("Median: ",np.median(arr))
print("std dev: ", np.std(arr))

Mean:  110.0
Median:  65.0
std dev:  107.08252269472673


In [14]:
#Remove common items from array
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
arr = np.isin(a,b)
print(arr)
l = a[~arr]
print(l)

[False False False False  True]
[1 2 3 4]


In [15]:
#Normalize a NumPy array (values between 0 and 1)
arr = np.array([10, 20, 30, 40, 50])
print((arr - arr.min()) / (arr.max() - arr.min()))

[0.   0.25 0.5  0.75 1.  ]


In [17]:
#Get the positions where elements of array a and b match
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 4, 3, 7, 8])

print(np.where(a == b))

(array([0, 2]),)


In [20]:
#Extract numbers from an array
arr = np.arange(15)
print(arr[(arr > 5) & (arr <= 10)])

[ 6  7  8  9 10]


In [24]:
#Create a random 3×2 matrix and find its maximum and minimum values
arr = np.random.rand(3,2)
print(arr)
print(np.min(arr), np.max(arr))

[[0.30606433 0.16251248]
 [0.88058186 0.3489299 ]
 [0.99041622 0.07430872]]
0.0743087168484845 0.9904162246326207


In [25]:
#Sorting a NumPy array based on a specific column
arr = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
sort_ind = arr[:,1].argsort()
sort_arr = arr[sort_ind]
print(sort_arr)

[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [30]:
#Delete and Insert a Column in a NumPy Array
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])
newcol = np.array([10, 10, 10])
print(arr)
deleted = np.delete(arr, 1, axis = 1)
print(deleted)
print(np.insert(deleted, 1, newcol, axis = 1))

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[34 73]
 [82 12]
 [53 66]]
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [32]:
#Swap column 1 and 2 in a 2D array
arr = np.arange(9).reshape(3, 3)
print(arr)

arr[:,[1,2]] = arr[:,[2,1]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 1]
 [3 5 4]
 [6 8 7]]
